--============================================================================
-- PERDAS - Drogaria Araujo				
--
-- Data de criação:		2015/02/19						
-- Autor:			    Thiago Faria						
-- Banco:			    DB_STAGING_AREA
-- Módulo/Sistema:		BI
-- Objetivo:			Carrega informações do Kardex na tabela mensal de perdas gerenciais
-- Retorno:				NA
-- Parâmetros:			NA
-- Exemplo execucao:	NA
-- Plano de Testes:		Final do script
--============================================================================

----------------------------------------------------------------------------------------------------------------------------------------------------
/* CONSULTA INFORMAÇÕES DE ACERTO DE ESTOQUE
GRÃO DA TABELA: AEK_DAT_MOV, AEK_COD_LJA, AEK_IDT_CRI, AEK_TIP_MOV, AEK_COD_USU
*/
----------------------------------------------------------------------------------------------------------------------------------------------------


SELECT 
KAFI_DT_OCR AS AEK_DAT_OCR,
CAST(CONVERT(VARCHAR(8),KAFI_DT_MOV, 112) AS DATETIME) AS AEK_DAT_MOV,
KAFI_CD_FILIAL AS AEK_COD_LJA,
KAFI_CD_PRODUTO AS AEK_COD_PRD,
KAFI_FL_DEUCRIA AS AEK_IDT_CRI,
KAFI_TP_MOV AS AEK_TIP_MOV,
XXXX_CD_USUALT AS AEK_COD_USU,
ISNULL(MOAA_SQ_MOTIVOAJUS,0) AS AEK_SEQ_MOTAJT,
SUM(CAST(CASE 
			WHEN KAFI_TP_MOV IN ('SA', 'SO', 'S9', 'S6') THEN KAFI_QT_MOV * 1
			WHEN KAFI_TP_MOV IN ('E9', 'EA', 'EO', 'E6') THEN KAFI_QT_MOV * -1
		END AS INT)) AS AEK_QTD_ITM,
SUM(CAST(CASE
			WHEN KAFI_TP_MOV IN ('SA', 'SO', 'S9', 'S6') THEN KAFI_QT_MOV * KAFI_VL_PREVEN * 1
			WHEN KAFI_TP_MOV IN ('E9', 'EA', 'EO', 'E6') THEN KAFI_QT_MOV * KAFI_VL_PREVEN * -1
		END AS NUMERIC(13,2))) AS AEK_VAL_VDA,
SUM(CAST(CASE
			WHEN KAFI_TP_MOV IN ('SA', 'SO', 'S9', 'S6') THEN KAFI_QT_MOV * KAFI_VL_CMPG * 1
			WHEN KAFI_TP_MOV IN ('E9', 'EA', 'EO', 'E6') THEN KAFI_QT_MOV * KAFI_VL_CMPG * -1
		END AS NUMERIC(13,2))) AS AEK_VAL_CMPG,
SUM(CAST(CASE
			WHEN KAFI_TP_MOV IN ('SA', 'SO', 'S9', 'S6') THEN KAFI_QT_MOV * KAFI_VL_CMPCCICMS * 1
			WHEN KAFI_TP_MOV IN ('E9', 'EA', 'EO', 'E6') THEN KAFI_QT_MOV * KAFI_VL_CMPCCICMS * -1
		END AS NUMERIC(13,2))) AS AEK_VAL_CMPCCOMABTICMS,
0 AS AEK_SRK_TPOANOMES,
0 AS AEK_SRK_LJAFIS,
0 AS AEK_SRK_PRD,
0 AS AEK_SRK_PRDGC,
0 AS AEK_SRK_MOTESTTRN,
0 AS AEK_SRK_USU,
0 AS AEK_SRK_MOTAJT,
CASE 
	WHEN (ISNULL(KAFI_TX_NR_DOCTO,'(Dado não disponível)') = '') THEN '(Dado não disponível)' 
	ELSE ISNULL(KAFI_TX_NR_DOCTO,'(Dado não disponível)') 
END AS AEK_COD_NUMDOC,
0 AS AEK_SRK_NUMDOC
FROM BUIODSDBS..KARDEX_FILIAL (NOLOCK)
WHERE CONVERT(VARCHAR(6),KAFI_DT_OCR, 112) = ? 
AND KAFI_TP_MOV IN (	-- INVENTÁRIO
						'SA', 'E9', 'EA', 'S9',
						-- OUTROS AJUSTES
						'SO', 'EO', 'S6', 'E6'
) AND KAFI_FL_DEUCRIA <> 'S'
GROUP BY 
KAFI_DT_OCR,
CAST(CONVERT(VARCHAR(8),KAFI_DT_MOV, 112) AS DATETIME),
KAFI_CD_FILIAL,
KAFI_CD_PRODUTO,
KAFI_FL_DEUCRIA,
KAFI_TP_MOV,
XXXX_CD_USUALT,
MOAA_SQ_MOTIVOAJUS,
KAFI_TX_NR_DOCTO

UNION ALL

SELECT 
KAFI_DT_OCR AS AEK_DAT_OCR,
CAST(CONVERT(VARCHAR(8),KAFI_DT_MOV, 112) AS DATETIME) AS AEK_DAT_MOV,
KAFI_CD_FILIAL AS AEK_COD_LJA,
KAFI_CD_PRODUTO AS AEK_COD_PRD,
KAFI_FL_DEUCRIA AS AEK_IDT_CRI,
KAFI_TP_MOV AS AEK_TIP_MOV,
XXXX_CD_USUALT AS AEK_COD_USU,
ISNULL(MOAA_SQ_MOTIVOAJUS,0) AS AEK_SEQ_MOTAJT,
SUM(CAST((KAFI_QT_MOV - KAFI_QT_SALDO_ANT) * -1 AS INT)) AS AEK_QTD_ITM,
SUM(CAST(((KAFI_QT_MOV - KAFI_QT_SALDO_ANT) * KAFI_VL_PREVEN) * -1 AS NUMERIC(13,2))) AS AEK_VAL_VDA,
SUM(CAST(((KAFI_QT_MOV - KAFI_QT_SALDO_ANT) * KAFI_VL_CMPG) * -1 AS NUMERIC(13,2))) AS AEK_VAL_CMPG,
SUM(CAST(((KAFI_QT_MOV - KAFI_QT_SALDO_ANT) * KAFI_VL_CMPCCICMS) * -1 AS NUMERIC(13,2))) AS AEK_VAL_CMPCCOMABTICMS,
0 AS AEK_SRK_TPOANOMES,
0 AS AEK_SRK_LJAFIS,
0 AS AEK_SRK_PRD,
0 AS AEK_SRK_PRDGC,
0 AS AEK_SRK_MOTESTTRN,
0 AS AEK_SRK_USU,
0 AS AEK_SRK_MOTAJT,
CASE WHEN (ISNULL(KAFI_TX_NR_DOCTO,'(Dado não disponível)') = '') THEN '(Dado não disponível)' ELSE ISNULL(KAFI_TX_NR_DOCTO,'(Dado não disponível)') END AS AEK_COD_NUMDOC,
0 AS AEK_SRK_NUMDOC
FROM BUIODSDBS..KARDEX_FILIAL (NOLOCK)
WHERE CONVERT(VARCHAR(6),KAFI_DT_OCR, 112) =  ?
AND KAFI_FL_DEUCRIA = 'S'
GROUP BY
KAFI_DT_OCR,
CAST(CONVERT(VARCHAR(8),KAFI_DT_MOV, 112) AS DATETIME),
KAFI_CD_FILIAL,
KAFI_CD_PRODUTO,
KAFI_FL_DEUCRIA,
KAFI_TP_MOV,
XXXX_CD_USUALT,
MOAA_SQ_MOTIVOAJUS,
KAFI_TX_NR_DOCTO

/*
select MAJ_COD_MOTAJT,TME_NOM_MOT,TME_COD_TRN, MAJ_NOM_MOTAJT,  sum(AJK_QTD_ITM)
from FAT_AJK_AJTESTKARDEX
	join DIM_MAJ_MOTAJT
		on AJK_SRK_MOTAJT = MAJ_SRK_MOTAJT
	join DIM_TME_TRNMOTEST
		on TME_SRK_TRNMOTEST= AJK_SRK_MOTESTTRN
where AJK_DAT_MOV >='20170101' 
and AJK_DAT_MOV <='20170131'
group by MAJ_COD_MOTAJT,TME_NOM_MOT,TME_COD_TRN, MAJ_NOM_MOTAJT
order by TME_COD_TRN


select * from BIDASA.dbo.DIM_MAJ_MOTAJT
select * from BIDASA.dbo.DIM_TME_TRNMOTEST



*/