DECLARE @STATUS_EXEC INT

SELECT @STATUS_EXEC = A.StatusPacote
FROM BUICTRDBS.dbo.Audit_LogExecucaoPacote A (NOLOCK)
WHERE A.HorarioInicio = (SELECT MAX(B.HorarioInicio) FROM BUICTRDBS.dbo.Audit_LogExecucaoPacote B (NOLOCK))


SELECT DISTINCT RUN_STATUS, @STATUS_EXEC AS ULT_STATUS_EXEC
FROM MSDB.dbo.SYSJOBS NJOB (NOLOCK)
JOIN MSDB.dbo.SYSJOBHISTORY JOB (NOLOCK)
	ON NJOB.job_id = JOB.job_id
WHERE NJOB.NAME = 'BI_ETL_CARGA'
	AND	RUN_DATE >= CONVERT(INT,CONVERT(CHAR(8),GETDATE(),112))


SELECT A.DESCRICAOPACOTE, TEDT_NR_DIA_SEMANA,
A.HORARIOINICIO, 
A.HORARIOFIM, 
DATEDIFF(MI,HORARIOINICIO,HORARIOFIM) AS DIFMINUTOS,
CASE STATUSPACOTE WHEN 2 THEN 'ERRO' WHEN 0 THEN 'EM ANDAMENTO' ELSE 'SUCESSO' END ST,
A.ERROTAREFA, USUARIOEXEC
FROM BUICTRDBS.dbo.Audit_LogExecucaoPacote A (NOLOCK)
	join bidasa..DIM_TEMPO_data
		on TEDT_DT_TEMPO_DATA = cONVERT(VARCHAR(8),HORARIOINICIO,112)
WHERE HORARIOINICIO >=CONVERT(VARCHAR(8),DATEADD(DD,-15,GETDATE()),112)
AND HORARIOINICIO <=CONVERT(VARCHAR(8),DATEADD(DD,1,GETDATE()),112)
--HORARIOINICIO >= CONVERT(CHAR(8),GETDATE(),112)
--AND STATUSPACOTE IN (0,2)
AND DESCRICAOPACOTE LIKE'%BUI_DIM_CLIENTES%'
AND USUARIOEXEC IN ('ARAUJOCORP\svc_sqlclbi')
AND STATUSPACOTE = 1 --SUCESSO
ORDER BY A.HORARIOINICIO ASC