/*ATUALIZA O TEMPO MÉDIO DE CARGA DE CADA PACOTE*/
IF OBJECT_ID ('TEMPDB..#TMP_CALCULO_REMOVER_OUTLIER') IS NOT NULL
	DROP TABLE TEMPDB..#TMP_CALCULO_REMOVER_OUTLIER

DECLARE @DATAINI VARCHAR(8) = '20180101'
DECLARE @DATAFIM VARCHAR(8) = '20180131'

;WITH TEMPO_MEDIO
AS (
		SELECT 
		A.DESCRICAOPACOTE, 
		ROUND(AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)),2) AS AVG_TOT_MINUTOS,
		ROUND(STDEV(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)),2) AS STDEV_TOT_MINUTOS
		FROM BUICTRDBS.DBO.AUDIT_LOGEXECUCAOPACOTE A (NOLOCK)
		WHERE HORARIOINICIO >= @DATAINI
		AND HORARIOINICIO <= @DATAFIM
		AND USUARIOEXEC IN ('ARAUJOCORP\SVC_SQLCLBI')
		--AND A.DESCRICAOPACOTE = 'BUI_ABS_FAT_ABASTECIMENTO_LOJA'
		AND DESCRICAOPACOTE IS NOT NULL
 		GROUP BY A.DESCRICAOPACOTE
)
SELECT 
DESCRICAOPACOTE,
AVG_TOT_MINUTOS,
STDEV_TOT_MINUTOS,
AVG_TOT_MINUTOS - (2*STDEV_TOT_MINUTOS) OUTLIER_MIN,
AVG_TOT_MINUTOS + (2*STDEV_TOT_MINUTOS) OUTLIER_MAX
INTO #TMP_CALCULO_REMOVER_OUTLIER
FROM TEMPO_MEDIO
ORDER BY DESCRICAOPACOTE

SELECT 
GETDATE() DATA_INSERT,
GETDATE() DATA_UPDATE,
A.DESCRICAOPACOTE, 
CAST(CASE WHEN AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST(AVG(DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS NUMERIC(8,2)) TEMPO_MEDIO_MIN,
CAST((CAST(CASE WHEN AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST(AVG(DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS INT))/60 AS VARCHAR(6)) + ':' + 
CAST((CAST(CASE WHEN AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST(AVG(DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS INT)) AS VARCHAR(20))TEMPO_MEDIO_HOR,
MAX(HORARIOFIM) DAT_ULT_EXECUCAO
FROM BUICTRDBS.DBO.AUDIT_LOGEXECUCAOPACOTE A (NOLOCK)
	JOIN #TMP_CALCULO_REMOVER_OUTLIER B
		ON A.DESCRICAOPACOTE = B.DESCRICAOPACOTE
WHERE HORARIOINICIO >=DATEADD(M,-6,GETDATE())
AND HORARIOINICIO <=GETDATE()
AND USUARIOEXEC IN ('ARAUJOCORP\SVC_SQLCLBI')
AND DATEDIFF(MI,HORARIOINICIO,HORARIOFIM) >= OUTLIER_MIN
AND DATEDIFF(MI,HORARIOINICIO,HORARIOFIM) <= OUTLIER_MAX
AND A.DESCRICAOPACOTE IS NOT NULL
--AND A.DESCRICAOPACOTE = 'BUI_PDA_FAT_INVENTARIO_SETORIZADO'
GROUP BY A.DESCRICAOPACOTE
--ORDER BY A.DESCRICAOPACOTE DESC
ORDER BY CAST(CASE WHEN AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST(AVG(DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS NUMERIC(8,2))  DESC
		
/*

SELECT 
A.DESCRICAOPACOTE, 
HORARIOINICIO,
HORARIOFIM,
DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)
FROM BUICTRDBS.DBO.AUDIT_LOGEXECUCAOPACOTE A (NOLOCK)
	JOIN #TMP_CALCULO_OUTLIER B
		ON A.DESCRICAOPACOTE = B.DESCRICAOPACOTE
WHERE HORARIOINICIO >= '2018-01-01 01:18:00.277'
AND HORARIOINICIO <='2018-05-29 01:18:00.277'
AND USUARIOEXEC IN ('ARAUJOCORP\SVC_SQLCLBI')
AND DATEDIFF(MI,HORARIOINICIO,HORARIOFIM) >= OUTLIER_MIN
AND DATEDIFF(MI,HORARIOINICIO,HORARIOFIM) <= OUTLIER_MAX
AND A.DESCRICAOPACOTE = 'BUI_WFM_INDICADORES'
AND A.DESCRICAOPACOTE IS NOT NULL
ORDER BY DATEDIFF(MI,HORARIOINICIO,HORARIOFIM) DESC


*/