DECLARE @STATUS_EXEC INT

SELECT @STATUS_EXEC = A.StatusPacote
FROM BUICTRDBS.dbo.Audit_LogExecucaoPacote A (NOLOCK)
WHERE A.HorarioInicio = (SELECT MAX(B.HorarioInicio) FROM BUICTRDBS.dbo.Audit_LogExecucaoPacote B (NOLOCK))


SELECT DISTINCT RUN_STATUS, @STATUS_EXEC AS ULT_STATUS_EXEC
FROM MSDB.dbo.SYSJOBS NJOB (NOLOCK)
JOIN MSDB.dbo.SYSJOBHISTORY JOB (NOLOCK)
	ON NJOB.job_id = JOB.job_id
WHERE NJOB.NAME = 'BI_ETL_CARGA'
	AND	RUN_DATE >= CONVERT(INT,CONVERT(CHAR(8),GETDATE(),112))


SELECT A.DESCRICAOPACOTE, 
A.HORARIOINICIO, 
A.HORARIOFIM, 
DATEDIFF(MI,HORARIOINICIO,HORARIOFIM) AS DIFMINUTOS,
CASE STATUSPACOTE WHEN 2 THEN 'ERRO' WHEN 0 THEN 'EM ANDAMENTO' ELSE 'SUCESSO' END ST,
A.ERROTAREFA, USUARIOEXEC
FROM BUICTRDBS.dbo.Audit_LogExecucaoPacote A (NOLOCK)
WHERE HORARIOINICIO >= '2018-01-01 01:18:00.277'
AND HORARIOINICIO <='2018-03-06 01:18:00.277'
--HORARIOINICIO >= CONVERT(CHAR(8),GETDATE(),112)
--AND STATUSPACOTE IN (0,2)
AND DESCRICAOPACOTE LIKE'%BUI_DIM_CLIENTES%'
AND USUARIOEXEC IN ('ARAUJOCORP\svc_sqlclbi')
ORDER BY A.HORARIOINICIO ASC