USE BUICTRDBS

DROP TABLE CTR_IDC_IDC
DROP TABLE CTR_ART_RELGRCTERNEG
DROP TABLE CTR_CAR_CTRACSREL
DROP TABLE CTR_OPC_ORDPCTCGA
DROP TABLE CTR_SJC_STAJOBCGA --VER COM JULIO
DROP TABLE CTR_STA_STAVLDASS --VER COM JULIO
DROP TABLE CTR_VLD_VLDASS
DROP TABLE TBL_CASSI --VER COM JULIO