/*
/*PROCESSOS COM ERRO NO DIA*/
SELECT A.DESCRICAOPACOTE, 
A.HORARIOINICIO, 
A.HORARIOFIM, 
DATEDIFF(MI,HORARIOINICIO,HORARIOFIM) AS DIFMINUTOS,
CASE STATUSPACOTE WHEN 2 THEN 'ERRO' WHEN 0 THEN 'EM ANDAMENTO' ELSE 'SUCESSO' END ST,
A.ERROTAREFA, USUARIOEXEC
FROM BUICTRDBS.dbo.Audit_LogExecucaoPacote A (NOLOCK)
WHERE CONVERT(VARCHAR(8),HORARIOINICIO,112) = CONVERT(VARCHAR(8),GETDATE(),112)
AND USUARIOEXEC IN ('ARAUJOCORP\svc_sqlclbi')
AND STATUSPACOTE = 2
ORDER BY A.HORARIOINICIO ASC

/*HORÁRIO DE TÉRMINO DA CARGA BI_ETL_CARGA*/
SELECT DESCRICAOPACOTE, HORARIOFIM HORÁRIO_FIM
FROM BUICTRDBS.DBO.AUDIT_LOGEXECUCAOPACOTE A (NOLOCK)
WHERE CONVERT(VARCHAR(8),HORARIOINICIO,112) = CONVERT(VARCHAR(8),GETDATE(),112)
AND USUARIOEXEC IN ('ARAUJOCORP\SVC_SQLCLBI')
AND DESCRICAOPACOTE LIKE ('%RVN%')
AND STATUSPACOTE = 1
ORDER BY HORARIOFIM

SELECT SJ.NAME,
SH.RUN_DATE,
SH.STEP_NAME,
STUFF(STUFF(RIGHT(REPLICATE('0', 6) +  CAST(SH.RUN_TIME AS VARCHAR(6)), 6), 3, 0, ':'), 6, 0, ':') 'RUN_TIME',
STUFF(STUFF(STUFF(RIGHT(REPLICATE('0', 8) + CAST(SH.RUN_DURATION AS VARCHAR(8)), 8), 3, 0, ':'), 6, 0, ':'), 9, 0, ':') 'RUN_DURATION (DD:HH:MM:SS)  '
FROM MSDB.DBO.SYSJOBS SJ
JOIN MSDB.DBO.SYSJOBHISTORY SH
ON SJ.JOB_ID = SH.JOB_ID
WHERE SJ.NAME = 'BI_ETL_CARGA_REVIONICS_DIARIO'
AND SH.RUN_DATE =  CONVERT(VARCHAR(8),GETDATE(),112)
*/

/*ATUALIZA O TEMPO MÉDIO DE CARGA DE CADA PACOTE*/
IF OBJECT_ID ('TEMPDB..#TMP_CALCULO_REMOVER_OUTLIER') IS NOT NULL
	DROP TABLE TEMPDB..#TMP_CALCULO_REMOVER_OUTLIER

IF OBJECT_ID ('TEMPDB..#TMP_TEMPO_MEDIO_PACOTES') IS NOT NULL
	DROP TABLE TEMPDB..#TMP_TEMPO_MEDIO_PACOTES

DECLARE @DATAINI VARCHAR(8) = CONVERT(VARCHAR(8),DATEADD(MM,-6,GETDATE()),112) --ULT_6MESES
DECLARE @DATAFIM VARCHAR(8) = CONVERT(VARCHAR(8),GETDATE(),112) --DATA_HOJE

;WITH TEMPO_MEDIO
AS (
		SELECT 
		A.DESCRICAOPACOTE, 
		ROUND(AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)),2) AS AVG_TOT_MINUTOS,
		ROUND(STDEV(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)),2) AS STDEV_TOT_MINUTOS
		FROM BUICTRDBS.DBO.AUDIT_LOGEXECUCAOPACOTE A (NOLOCK)
		WHERE HORARIOINICIO >= @DATAINI
		AND HORARIOINICIO <= @DATAFIM
		AND USUARIOEXEC IN ('ARAUJOCORP\SVC_SQLCLBI')
		--AND A.DESCRICAOPACOTE = 'BUI_ABS_FAT_ABASTECIMENTO_LOJA'
		AND DESCRICAOPACOTE IS NOT NULL
 		GROUP BY A.DESCRICAOPACOTE
)
SELECT 
DESCRICAOPACOTE,
AVG_TOT_MINUTOS,
STDEV_TOT_MINUTOS,
AVG_TOT_MINUTOS - (2*STDEV_TOT_MINUTOS) OUTLIER_MIN,
AVG_TOT_MINUTOS + (2*STDEV_TOT_MINUTOS) OUTLIER_MAX
INTO #TMP_CALCULO_REMOVER_OUTLIER
FROM TEMPO_MEDIO
ORDER BY DESCRICAOPACOTE

SELECT 
GETDATE() DATA_INSERT,
GETDATE() DATA_UPDATE,
A.DESCRICAOPACOTE, 
CAST(CASE WHEN AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST(AVG(DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS NUMERIC(8,2)) TEMPO_MEDIO_MIN,
CAST((CAST(CASE WHEN AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST(AVG(DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS INT))/60 AS VARCHAR(6)) + ':' + 
CAST((CAST(CASE WHEN AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST(AVG(DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS INT)) AS VARCHAR(20))TEMPO_MEDIO_HOR,
MAX(HORARIOFIM) DAT_ULT_EXECUCAO_6MESES
INTO #TMP_TEMPO_MEDIO_PACOTES
FROM BUICTRDBS.DBO.AUDIT_LOGEXECUCAOPACOTE A (NOLOCK)
	JOIN #TMP_CALCULO_REMOVER_OUTLIER B
		ON A.DESCRICAOPACOTE = B.DESCRICAOPACOTE
WHERE HORARIOINICIO >=DATEADD(M,-6,GETDATE())
AND HORARIOINICIO <=GETDATE()
--AND USUARIOEXEC IN ('ARAUJOCORP\SVC_SQLCLBI')
AND DATEDIFF(MI,HORARIOINICIO,HORARIOFIM) >= OUTLIER_MIN
AND DATEDIFF(MI,HORARIOINICIO,HORARIOFIM) <= OUTLIER_MAX
AND A.DESCRICAOPACOTE IS NOT NULL
GROUP BY A.DESCRICAOPACOTE
ORDER BY CAST(CASE WHEN AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST(AVG(DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS NUMERIC(8,2))  DESC

DECLARE @JOB_RVN DATETIME = (
								SELECT 
								MAX(CONVERT(DATETIME, STUFF(STUFF(STUFF(CAST(SH.RUN_DATE AS VARCHAR) + CAST(REPLICATE('0',6 -LEN(SH.RUN_TIME)) +RTRIM(SH.RUN_TIME)AS VARCHAR) ,13,0,':'),11,0,':'),9,0,' ')))
								FROM MSDB.DBO.SYSJOBS SJ
								JOIN MSDB.DBO.SYSJOBHISTORY SH
								ON SJ.JOB_ID = SH.JOB_ID
								WHERE SJ.NAME = 'BI_ETL_CARGA_REVIONICS_DIARIO'
								AND SH.RUN_DATE =  CONVERT(VARCHAR(8),GETDATE(),112)
)

DECLARE @JOB_ETL_CARGA DATETIME = (
								SELECT 
								MAX(CONVERT(DATETIME, STUFF(STUFF(STUFF(CAST(SH.RUN_DATE AS VARCHAR) + CAST(REPLICATE('0',6 -LEN(SH.RUN_TIME)) +RTRIM(SH.RUN_TIME)AS VARCHAR) ,13,0,':'),11,0,':'),9,0,' ')))
								FROM MSDB.DBO.SYSJOBS SJ
								JOIN MSDB.DBO.SYSJOBHISTORY SH
								ON SJ.JOB_ID = SH.JOB_ID
								WHERE SJ.NAME = 'BI_ETL_CARGA'
								AND SH.RUN_DATE =  CONVERT(VARCHAR(8),GETDATE(),112)
)

/*HORÁRIO DE TÉRMINO DA CARGA BI_ETL_CARGA*/
SELECT 
	CASE 
		WHEN DESCRICAOPACOTE = 'BUI_SEQ_FATO' THEN 'FATOS'
		WHEN DESCRICAOPACOTE = 'BUI_SEQ_CUBOS' THEN 'CUBOS' 
		WHEN DESCRICAOPACOTE = 'BUI_SEQ_WFM_ENVIO' THEN 'WFM' 
		WHEN DESCRICAOPACOTE LIKE ('%RVN%') THEN 'RVN' END ASSUNTO, 
MAX(HORARIOFIM) HORÁRIO_FIM 
FROM BUICTRDBS.DBO.AUDIT_LOGEXECUCAOPACOTE A (NOLOCK)
WHERE CONVERT(VARCHAR(8),HORARIOINICIO,112) = CONVERT(VARCHAR(8),GETDATE(),112)
AND USUARIOEXEC IN ('ARAUJOCORP\SVC_SQLCLBI')
AND DESCRICAOPACOTE IN ('BUI_SEQ_FATO', 'BUI_SEQ_CUBOS', 'BUI_SEQ_WFM_ENVIO')
OR DESCRICAOPACOTE LIKE ('%RVN%')
AND STATUSPACOTE = 1
AND HORARIOINICIO <= @JOB_RVN
GROUP BY 
CASE WHEN DESCRICAOPACOTE = 'BUI_SEQ_FATO' THEN 'FATOS'
WHEN DESCRICAOPACOTE = 'BUI_SEQ_CUBOS' THEN 'CUBOS' 
WHEN DESCRICAOPACOTE = 'BUI_SEQ_WFM_ENVIO' THEN 'WFM' 
WHEN DESCRICAOPACOTE LIKE ('%RVN%') THEN 'RVN' END
ORDER BY MAX(HORARIOFIM)

/*
/*PROCESSOS QUE APRESENTARAM ERRO DURANTE O PROCESSO DE CARGA DIÁRIA*/
SELECT COUNT(1) QTD_REGISTROS, MAX(HORARIOINICIO) DATA_HORA_ULT_ERRO
FROM BUICTRDBS.DBO.AUDIT_LOGEXECUCAOPACOTE A (NOLOCK)
WHERE CONVERT(VARCHAR(8),HORARIOINICIO,112) = CONVERT(VARCHAR(8),GETDATE(),112)
AND USUARIOEXEC IN ('ARAUJOCORP\SVC_SQLCLBI')
AND STATUSPACOTE = 2
AND HORARIOINICIO <= @JOB_ETL_CARGA
*/

/*RELAÇÃO DE TODOS OS PACOTES DE CARGA, UTILIZA O TEMPO MÉDIO, REMOVENDO OUTLIERS*/
SELECT A.DESCRICAOPACOTE NOM_PACOTE,
A.TEMPO_MEDIO_MIN, 
A.TEMPO_MEDIO_HOR,
A.DAT_ULT_EXECUCAO_6MESES,
B.STATUSPACOTE COD_STATUS_ATUAL, 
CASE B.STATUSPACOTE 
	WHEN 2 THEN 'ERRO' 
	WHEN 0 THEN 'EM ANDAMENTO' 
	WHEN 1 THEN 'SUCESSO' 
	ELSE 'NÃO EXECUTADO' END NOM_STATUS_ATUAL,
B.HORARIOINICIO HOR_INI_ATUAL, 
B.HORARIOFIM HOR_FIM_ATUAL,
CAST(CASE WHEN (DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST((DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE (DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS NUMERIC(8,2)) TEMPO_MEDIO_MIN_ATUAL,
CAST((CAST(CASE WHEN (DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST((DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE (DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS INT))/60 AS VARCHAR(6)) + ':' + 
CAST((CAST(CASE WHEN (DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST((DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE (DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS INT)) AS VARCHAR(20))TEMPO_MEDIO_HOR_ATUAL,
B.USUARIOEXEC USU_EXEC_ATUAL
FROM #TMP_TEMPO_MEDIO_PACOTES A
	LEFT JOIN BUICTRDBS.DBO.AUDIT_LOGEXECUCAOPACOTE B (NOLOCK)
		ON A.DESCRICAOPACOTE = B.DESCRICAOPACOTE
		AND CONVERT(VARCHAR(8),B.HORARIOINICIO,112) >= CONVERT(VARCHAR(8),GETDATE(),112)
WHERE B.STATUSPACOTE IS NOT NULL
--and  B.STATUSPACOTE = 2
--ORDER BY ISNULL(B.HORARIOINICIO,'20200101'), A.DESCRICAOPACOTE DESC
ORDER BY CAST(CASE WHEN (DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST((DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE (DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS NUMERIC(8,2)) DESC
