/*DECLARE @STATUS_EXEC INT

SELECT @STATUS_EXEC = A.StatusPacote
FROM BUICTRDBS.dbo.Audit_LogExecucaoPacote A (NOLOCK)
WHERE A.HorarioInicio = (SELECT MAX(B.HorarioInicio) FROM BUICTRDBS.dbo.Audit_LogExecucaoPacote B (NOLOCK))


SELECT DISTINCT RUN_STATUS, @STATUS_EXEC AS ULT_STATUS_EXEC
FROM MSDB.dbo.SYSJOBS NJOB (NOLOCK)
JOIN MSDB.dbo.SYSJOBHISTORY JOB (NOLOCK)
	ON NJOB.job_id = JOB.job_id
WHERE NJOB.NAME = 'BI_ETL_CARGA'
	AND	RUN_DATE >= CONVERT(INT,CONVERT(CHAR(8),GETDATE(),112))

*/


SELECT A.DESCRICAOPACOTE, 
A.HORARIOINICIO, 
A.HORARIOFIM, 
DATEDIFF(MI,HORARIOINICIO,HORARIOFIM) AS DIFMINUTOS,
CASE STATUSPACOTE WHEN 2 THEN 'ERRO' WHEN 0 THEN 'EM ANDAMENTO' ELSE 'SUCESSO' END ST,
A.ERROTAREFA, USUARIOEXEC
FROM BUICTRDBS.dbo.Audit_LogExecucaoPacote A (NOLOCK)
WHERE HORARIOINICIO >= '2018-06-01 01:18:00.277'
AND HORARIOINICIO <='2018-06-21 01:18:00.277'
--WHERE HORARIOINICIO >= CONVERT(CHAR(8),GETDATE(),112)
--AND STATUSPACOTE IN (2)
AND DESCRICAOPACOTE LIKE'%BUI_CMP_FAT_COMPRAS%'
--AND USUARIOEXEC IN ('ARAUJOCORP\svc_sqlclbi')
ORDER BY A.HORARIOINICIO ASC

/*PACOTES COM ERRO NA CARGA DA MADRUGADA*/
SELECT A.DESCRICAOPACOTE, 
A.HORARIOINICIO, 
A.HORARIOFIM, 
DATEDIFF(MI,HORARIOINICIO,HORARIOFIM) AS DIFMINUTOS,
CASE STATUSPACOTE WHEN 2 THEN 'ERRO' WHEN 0 THEN 'EM ANDAMENTO' ELSE 'SUCESSO' END ST,
A.ERROTAREFA, USUARIOEXEC
FROM BUICTRDBS.dbo.Audit_LogExecucaoPacote A (NOLOCK)
WHERE HORARIOINICIO >= '2018-01-01 00:18:00.277'
AND HORARIOINICIO <='2018-07-06 05:18:00.277'
--WHERE HORARIOINICIO >= CONVERT(CHAR(8),GETDATE(),112)
--AND STATUSPACOTE IN (3)
AND DESCRICAOPACOTE LIKE'%BUI_VDA_FAT_RANKING_CAMPANHA_VENDAS%'
--AND USUARIOEXEC IN ('ARAUJOCORP\svc_sqlclbi')
ORDER BY A.HORARIOINICIO ASC