/*

STATUS PACOTE: SCG_STA_EXE 
*	STATUS = 0: EM EXECUÇÃO
*	STATUS = 1: SUCESSO
*	STATUS = 2: FALHA
*   STATUS = 3: CANCELADO          
*	STATUS = 4: NÃO INICIADO OU PAUSA

CONTROLE MANUAL: SCG_STA_CTRMNL
*	0 - SERÁ ATUALIZADO AUTOMATICAMENTE PELO SEQUENCIAMENTO DA CARGA
*	1 - VALOR FIXO, SÓ SERÁ ATUALIZADO NO DIA SEGUINTE

DATA ESTIMADA PARA TÉRMINO DO PROCESSO: 
SCG_DTH_FIMEXE

COMENTÁRIOS: 
SCG_DTH_FIMEXE

*/

USE BUICTRDBS	

UPDATE BUICTRDBS..CTR_SCG_STACGA
SET SCG_DTH_FIMEXE = '2018-06-28 05:30:00.000',
SCG_STA_CTRMNL = '1',
SCG_STA_EXE = 1
WHERE SCG_DES_SIS = 'RELATÓRIOS (PORTAL E INSIGHTS)'

UPDATE DBO.CTR_SCG_STACGA
SET SCG_DTH_FIMEXE = '2017-11-30 14:20:00.000',
SCG_STA_CTRMNL = '0',
SCG_STA_EXE = 0
WHERE SCG_DES_SIS = 'CUBOS OLAP'

UPDATE DBO.CTR_SCG_STACGA
SET SCG_DTH_FIMEXE = '2018-07-03 11:30:00.000',
SCG_STA_CTRMNL = '0',
SCG_STA_EXE = 1
WHERE SCG_DES_SIS = 'Painéis Qlikview'


UPDATE DBO.CTR_SCG_STACGA
SET SCG_DTH_FIMEXE =   '2016-07-29 09:25:00.000',
SCG_STA_CTRMNL ='0',
SCG_STA_EXE = 0
WHERE SCG_DES_SIS = 'RELATÓRIOS GEGEP (PORTAL E INSIGHTS)'


UPDATE DBO.CTR_SCG_STACGA
SET SCG_DTH_FIMEXE = '2016-05-06 10:20:00.000',
SCG_STA_CTRMNL = '0',
SCG_STA_EXE = 0
WHERE SCG_DES_SIS = 'Painéis Qlikview'


UPDATE DBO.CTR_SCG_STACGA
SET SCG_OBS_STAASS = ''
WHERE SCG_SEQ_SIS IN (1,2,4,5)


UPDATE DBO.CTR_SCG_STACGA
SET SCG_OBS_STAASS = null
WHERE SCG_SEQ_SIS IN (1,2,3,4)


UPDATE DBO.CTR_SCG_STACGA
SET SCG_OBS_STAASS = '* Os cubos de Recarga de Celular, Indicadores de Loja, Vendas Drogatel e Estoque não foram atualizados. No momento estão em manutenção pelo BI.'
--WHERE SCG_SEQ_SIS IN (1,2,3,4)
WHERE SCG_SEQ_SIS IN (3,4)
 
select * from CTR_SCG_STACGA

/*
INSERT INTO DBO.CTR_SCG_STACGA
SELECT GETDATE(),GETDATE(),'Qlikview (LB+)',getdate(),1,getdate(),0,''
*/

UPDATE DBO.CTR_SCG_STACGA
SET SCG_STA_CTRMNL = 0
WHERE SCG_SEQ_SIS IN (1,2)


/*
--SELECT * into #CTR_SCG_STACGA FROM CTR_SCG_STACGA
SELECT * FROM CTR_SCG_STACGA
--truncate table CTR_SCG_STACGA

insert into CTR_SCG_STACGA (
HDR_DTH_ATZ,
HDR_DTH_INS,
SCG_SEQ_SIS,
SCG_DES_SIS,
SCG_DAT_EXE,
SCG_STA_EXE,
SCG_DTH_FIMEXE,
SCG_STA_CTRMNL,
SCG_OBS_STAASS)
select HDR_DTH_ATZ,
HDR_DTH_INS,
0,
SCG_DES_SIS,
SCG_DAT_EXE,
SCG_STA_EXE,
SCG_DTH_FIMEXE,
SCG_STA_CTRMNL,
SCG_OBS_STAASS
from #CTR_SCG_STACGA




update CTR_SCG_STACGA
set SCG_SEQ_SIS = 3
where SCG_DES_SIS = 'Relatórios GEGEP (Portal e Insights)'


--EXEC CTR_STP_PNLCGA 'BUI_SEQ_CUBOS'


ALTER TABLE CTR_SCG_STACGA DROP CONSTRAINT CPK_CTR_SCG_STACGA

SET IDENTITY_UPDATE CTR_SCG_STACGA OFF
go
update CTR_SCG_STACGA
set SCG_SEQ_SIS = 2
where SCG_DES_SIS = 'RELATÓRIOS GEGEP (PORTAL E INSIGHTS)'

ALTER TABLE CTR_SCG_STACGA
DROP COLUMN SCG_SEQ_SIS;
*/