SELECT * FROM [DBO].[CTR_TOB_TIPOBJ] ORDER BY TOB_COD_TIPOBJ
--INSERT INTO [CTR_TOB_TIPOBJ] SELECT GETDATE(), GETDATE(), 16, 'Pacotes SSIS'

--DELETE [DBO].[CTR_OBD_OBJBCODAD] WHERE OBD_SEQ > 0 

DBCC CHECKIDENT ('CTR_OBD_OBJBCODAD', RESEED, 0) 
SELECT * FROM [DBO].[CTR_OBD_OBJBCODAD]
--WHERE HDR_DTH_INS >='20170101'

/*ATUALIZA O TEMPO MÉDIO DE CARGA*/
INSERT INTO [CTR_OBD_OBJBCODAD]
SELECT 
GETDATE(),
GETDATE(),
0,
A.DESCRICAOPACOTE, 
16,
A.HORARIOINICIO, 
A.HORARIOFIM, 
DATEDIFF(MI,HORARIOINICIO,HORARIOFIM) AS DIFMINUTOS,
CASE STATUSPACOTE WHEN 2 THEN 'ERRO' WHEN 0 THEN 'EM ANDAMENTO' ELSE 'SUCESSO' END ST,
A.ERROTAREFA, USUARIOEXEC
FROM BUICTRDBS.dbo.Audit_LogExecucaoPacote A (NOLOCK)
WHERE HORARIOINICIO >= '2018-01-01 01:18:00.277'
AND HORARIOINICIO <='2018-03-06 01:18:00.277'
--HORARIOINICIO >= CONVERT(CHAR(8),GETDATE(),112)
--AND STATUSPACOTE IN (0,2)
AND DESCRICAOPACOTE LIKE'%BUI_DIM_CLIENTES%'
AND USUARIOEXEC IN ('ARAUJOCORP\svc_sqlclbi')
ORDER BY A.HORARIOINICIO ASC



/*ATUALIZA O TEMPO MÉDIO DE CARGA*/
SELECT A.DESCRICAOPACOTE, 
A.HORARIOINICIO, 
A.HORARIOFIM, 
DATEDIFF(MI,HORARIOINICIO,HORARIOFIM) AS DIFMINUTOS,
CASE STATUSPACOTE WHEN 2 THEN 'ERRO' WHEN 0 THEN 'EM ANDAMENTO' ELSE 'SUCESSO' END ST,
A.ERROTAREFA, USUARIOEXEC
FROM BUICTRDBS.dbo.Audit_LogExecucaoPacote A (NOLOCK)
WHERE HORARIOINICIO >= '2018-01-01 01:18:00.277'
AND HORARIOINICIO <='2018-03-06 01:18:00.277'
--HORARIOINICIO >= CONVERT(CHAR(8),GETDATE(),112)
--AND STATUSPACOTE IN (0,2)
AND DESCRICAOPACOTE LIKE'%BUI_DIM_CLIENTES%'
AND USUARIOEXEC IN ('ARAUJOCORP\svc_sqlclbi')
ORDER BY A.HORARIOINICIO ASC

