SELECT 'SQLSERVER' DBMS,T.TABLE_CATALOG,
T.TABLE_SCHEMA,
T.TABLE_NAME,
C.ORDINAL_POSITION,
C.COLUMN_NAME,
CASE WHEN IS_NULLABLE = 'NO' THEN 'Não' ELSE 'Sim' END IS_NULL,
CASE WHEN C.DATA_TYPE = 'varchar' THEN 'varchar('+cast(C.CHARACTER_MAXIMUM_LENGTH AS VARCHAR)+')' ELSE C.DATA_TYPE END DATA_TYPE,
K.COLUMN_NAME,
C.CHARACTER_MAXIMUM_LENGTH,
N.CONSTRAINT_TYPE,
K2.TABLE_SCHEMA,
K2.TABLE_NAME,
K2.COLUMN_NAME 
FROM INFORMATION_SCHEMA.TABLES T 
	LEFT JOIN INFORMATION_SCHEMA.COLUMNS C 
		ON T.TABLE_CATALOG=C.TABLE_CATALOG 
		AND T.TABLE_SCHEMA=C.TABLE_SCHEMA 
		AND T.TABLE_NAME=C.TABLE_NAME 
	LEFT JOIN(INFORMATION_SCHEMA.KEY_COLUMN_USAGE K 
				JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS N 
					ON K.CONSTRAINT_CATALOG=N.CONSTRAINT_CATALOG 
					AND K.CONSTRAINT_SCHEMA=N.CONSTRAINT_SCHEMA 
					AND K.CONSTRAINT_NAME=N.CONSTRAINT_NAME 
				LEFT JOIN INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS R 
					ON K.CONSTRAINT_CATALOG=R.CONSTRAINT_CATALOG 
					AND K.CONSTRAINT_SCHEMA=R.CONSTRAINT_SCHEMA 
					AND K.CONSTRAINT_NAME=R.CONSTRAINT_NAME
				)
		ON C.TABLE_CATALOG=K.TABLE_CATALOG 
		AND C.TABLE_SCHEMA=K.TABLE_SCHEMA 
		AND C.TABLE_NAME=K.TABLE_NAME 
		AND C.COLUMN_NAME=K.COLUMN_NAME 
	LEFT JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE K2 
		ON K.ORDINAL_POSITION=K2.ORDINAL_POSITION 
		AND R.UNIQUE_CONSTRAINT_CATALOG=K2.CONSTRAINT_CATALOG 
		AND R.UNIQUE_CONSTRAINT_SCHEMA=K2.CONSTRAINT_SCHEMA 
		AND R.UNIQUE_CONSTRAINT_NAME=K2.CONSTRAINT_NAME 
WHERE T.TABLE_TYPE='BASE TABLE'
--AND (C.COLUMN_NAME LIKE '%PRD%'
--OR T.TABLE_NAME LIKE '%PRD%')
AND T.TABLE_NAME LIKE '%PPR%'
ORDER BY  T.TABLE_NAME

/*
select * from INFORMATION_SCHEMA.COLUMNS
SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
*/