
/*ATUALIZA O TEMPO MÉDIO DE CARGA DE CADA PACOTE*/
IF OBJECT_ID ('DB_TEMP..TMP_MONITORDW_CALCULO_REMOVER_OUTLIER') IS NOT NULL
	DROP TABLE DB_TEMP..TMP_MONITORDW_CALCULO_REMOVER_OUTLIER

IF OBJECT_ID ('DB_TEMP..TMP_MONITORDW_TEMPO_MEDIO_PACOTES') IS NOT NULL
	DROP TABLE DB_TEMP..TMP_MONITORDW_TEMPO_MEDIO_PACOTES

DECLARE @DATAINI VARCHAR(8) = CONVERT(VARCHAR(8),DATEADD(MM,-6,GETDATE()),112) --ULT_6MESES
DECLARE @DATAFIM VARCHAR(8) = CONVERT(VARCHAR(8),GETDATE(),112) --DATA_HOJE

;WITH TEMPO_MEDIO
AS (
		SELECT 
		A.DESCRICAOPACOTE, 
		ROUND(AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)),2) AS AVG_TOT_MINUTOS,
		ROUND(STDEV(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)),2) AS STDEV_TOT_MINUTOS
		FROM BUICTRDBS.DBO.AUDIT_LOGEXECUCAOPACOTE A (NOLOCK)
		WHERE HORARIOINICIO >= @DATAINI
		AND HORARIOINICIO <= @DATAFIM
		AND USUARIOEXEC IN ('ARAUJOCORP\SVC_SQLCLBI')
		AND DESCRICAOPACOTE IS NOT NULL
 		GROUP BY A.DESCRICAOPACOTE
)
SELECT 
DESCRICAOPACOTE,
AVG_TOT_MINUTOS,
STDEV_TOT_MINUTOS,
AVG_TOT_MINUTOS - (2*STDEV_TOT_MINUTOS) OUTLIER_MIN,
AVG_TOT_MINUTOS + (2*STDEV_TOT_MINUTOS) OUTLIER_MAX
INTO DB_TEMP..TMP_MONITORDW_CALCULO_REMOVER_OUTLIER
FROM TEMPO_MEDIO
ORDER BY DESCRICAOPACOTE

SELECT 
GETDATE() DATA_INSERT,
GETDATE() DATA_UPDATE,
A.DESCRICAOPACOTE, 
CAST(CASE WHEN AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST(AVG(DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS NUMERIC(8,2)) TEMPO_MEDIO_MIN,
CAST((CAST(CASE WHEN AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST(AVG(DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS INT))/60 AS VARCHAR(6)) + ':' + 
CAST((CAST(CASE WHEN AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST(AVG(DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE AVG(DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS INT)) AS VARCHAR(20))TEMPO_MEDIO_HOR,
MAX(HORARIOFIM) DAT_ULT_EXECUCAO_6MESES
INTO DB_TEMP..TMP_MONITORDW_TEMPO_MEDIO_PACOTES
FROM BUICTRDBS.DBO.AUDIT_LOGEXECUCAOPACOTE A (NOLOCK)
	JOIN DB_TEMP..TMP_MONITORDW_CALCULO_REMOVER_OUTLIER B
		ON A.DESCRICAOPACOTE = B.DESCRICAOPACOTE
WHERE HORARIOINICIO >=DATEADD(M,-6,GETDATE())
AND HORARIOINICIO <=CONVERT(VARCHAR(8),GETDATE(),112)
AND DATEDIFF(MI,HORARIOINICIO,HORARIOFIM) >= OUTLIER_MIN
AND DATEDIFF(MI,HORARIOINICIO,HORARIOFIM) <= OUTLIER_MAX
AND A.DESCRICAOPACOTE IS NOT NULL
GROUP BY A.DESCRICAOPACOTE
ORDER BY MAX(HORARIOFIM)  DESC

/*RELAÇÃO DE TODOS OS PACOTES QUE EXECUTARAM NO DIA, UTILIZA A REFERÊNCIA DO TEMPO MÉDIO DOS ÚLTIMOS 6 MESES, REMOVENDO OUTLIERS*/
SELECT A.DESCRICAOPACOTE NOM_PACOTE,
A.TEMPO_MEDIO_MIN, 
A.TEMPO_MEDIO_HOR,
A.DAT_ULT_EXECUCAO_6MESES,
B.STATUSPACOTE COD_STATUS_ATUAL, 
CASE B.STATUSPACOTE 
	WHEN 2 THEN 'ERRO' 
	WHEN 0 THEN 'EM ANDAMENTO' 
	WHEN 1 THEN 'SUCESSO' 
	ELSE 'NÃO EXECUTADO' END NOM_STATUS_ATUAL,
B.HORARIOINICIO HOR_INI_ATUAL, 
B.HORARIOFIM HOR_FIM_ATUAL,
CAST(CASE WHEN (DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST((DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE (DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS NUMERIC(8,2)) TEMPO_MEDIO_MIN_ATUAL,
CAST((CAST(CASE WHEN (DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST((DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE (DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS INT))/60 AS VARCHAR(6)) + ':' + 
CAST((CAST(CASE WHEN (DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) = 0 
	THEN CAST((DATEDIFF(S,HORARIOINICIO,HORARIOFIM)) AS NUMERIC(8,2))/100 
		ELSE (DATEDIFF(MI,HORARIOINICIO,HORARIOFIM)) END AS INT)) AS VARCHAR(20))TEMPO_MEDIO_HOR_ATUAL,
B.USUARIOEXEC USU_EXEC_ATUAL
FROM DB_TEMP..TMP_MONITORDW_TEMPO_MEDIO_PACOTES A
	LEFT JOIN BUICTRDBS.DBO.AUDIT_LOGEXECUCAOPACOTE B (NOLOCK)
		ON A.DESCRICAOPACOTE = B.DESCRICAOPACOTE
		AND CONVERT(VARCHAR(8),B.HORARIOINICIO,112) >= CONVERT(VARCHAR(8),GETDATE(),112)
ORDER BY B.HORARIOINICIO DESC